# 当子模块多的时候，抽取一个公共的父.yml配置文件。也利于快速切换数据源。
server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zkactive/cloud-config.git
          search-paths:
            - cloud-config
      label: master

  #rabbitmq相关配置 15672是Web管理界面的端口；5672是MQ访问的端口
  # RabbitMQ配置。广播消息。Config服务端类似于微信公总号，而Config客户端类似于关注者。
  rabbitmq:
    host: test.lexiaotong.online      # host格式用ip||域名，不需要带http://协议
    port: 5672
    username: admin
    password: 123456

# 服务注册到eureka注册中心
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点。 外置Post接口手动更新。curl-x POST "http://localhost:3344/actuator/bus-refresh" （推荐）
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'