server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                  # mysql驱动包
#    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql6以及以上
#    driver-class-name: com.mysql.jdbc.Driver                    # jdbc连接mysql5
    url: jdbc:mysql://localhost:3306/zhongka?useUnicode=true&characterEncoding=utf-8&useSSL=false  # mysql5.7版本之后有安全加固
#    url: jdbc:mysql://localhost:3306/zhongka?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC       #mysql-version-5.0.96-community-nt
    username: root
    password: root

# 将支付模块注册进Eureka服务注册中心
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
     defaultZone: http://localhost:7001/eureka

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: cn.zk.springcloud.entities        # 所有Entity别名类所在包


