server:
  port: 8088

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.cn:7001/eureka

# 开启属性。用于服务降级，在注解@FeignClient中添加fallbackFactory属性值。
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。